pipeline{
    agent any 
    stages{
        stage("sonar-qube-quality-check"){
            agent{
                image{
                    docker 'openjdk:11'
                }
            }
            steps{
                script{
                    withSonarQubeEnv(credentialsId: 'sonar-token') {
                        sh '''
                        chmod +x gradlew
                        ./gradlew sonarqube
                        '''
                    }
                }
            }
        }
    }
}

    
